### PR TITLE
Npm update

### LINKED ISSUE #17: npm packages are outdated
need to run `npm update` and see if something broke

### PR DESCRIPTION
**Pull request by Akuli**
everything updated, including major versions (e.g. corejs 2.x.y --> 3.x.y)

some dependencies were deleted

everything seems to still work

fixes #17

### CODE REVIEW

**Comment by Akuli** [comment]
`@babel/plugin-proposal-class-properties` is weird, it doesn't have to be in `package.json` but it has to be mentioned in `webpack.config.js`

**Comment by PurpleMyst** [comment]
Have you tried starting from a clean node_modules? Does everything still work?

**Comment by Akuli** [comment]
The CI does it every time. I just tried it too and it worked.

**Comment by Akuli** [comment]
@PurpleMyst Can you review?

**Review by PurpleMyst — APPROVED** [review]
Looks good to me. I'm not sure what the implications of core-js 3 are, but it's all handled by webpack.

**Pull request merged**
